<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CineKros.Api</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../embedding/CineKros.Embedding/CineKros.Embedding.csproj" />
    <ProjectReference Include="../../etl/CineKros.Catalog.Importer/CineKros.Catalog.Importer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Prompts/movie-query-parser.md" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="RealProviders/query-parser-v4.md" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="RealProviders/query-parser.schema.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
